
## @{top_method}:@{partition_method}

```{r}
res = get_single_run(res_list, top_method = "@{top_method}", partition_method = "@{partition_method}")
res
```

Collect all plots

```{r @{top_method}-@{partition_method}-collect-plots, fig.width = 14, fig.height = 14*4/5, results = "hide", eval = FALSE}
collect_plots(res)
```

plots:

```{r @{top_method}-@{partition_method}-select-partition-number, results = "hide", fig.width = 10}
select_partition_number(res)
```

```{r}
get_stat(res)
```


```{r}
get_best_k(res)
```

Get classifications

```{r, results = "asis", echo = FALSE, include = TRUE}
@{ k = res_list@list[[1]]@k
qq("knitr_add_tab_item(\"get_class(res, k = @<k>)\", \"k = @<k>\")\n", code.pattern = "@<CODE>") }
knitr_insert_tabs()
```

```{r @{top_method}-@{partition_method}-consensus-heatmap, results = "asis", echo = FALSE, include = TRUE}
@{ k = res_list@list[[1]]@k
qq("knitr_add_tab_item(\"consensus_heatmap(res, k = @<k>)\", \"k = @<k>\")\n", code.pattern = "@<CODE>") }
knitr_insert_tabs()
```

```{r @{top_method}-@{partition_method}-membership-heatmap, results = "asis", echo = FALSE, include = TRUE}
@{ k = res_list@list[[1]]@k
qq("knitr_add_tab_item(\"membership_heatmap(res, k = @<k>)\", \"k = @<k>\")\n", code.pattern = "@<CODE>") }
knitr_insert_tabs()
```


```{r @{top_method}-@{partition_method}-signature, results = "asis", echo = FALSE, include = TRUE}
@{ k = res_list@list[[1]]@k
qq("knitr_add_tab_item(\"get_signatures(res, k = @<k>)\", \"k = @<k>\")\n", code.pattern = "@<CODE>") }
knitr_insert_tabs()
```

```{r @{top_method}-@{partition_method}-signature-density, results = "asis", echo = FALSE, include = TRUE}
@{ k = res_list@list[[1]]@k
qq("knitr_add_tab_item(\"signature_desity(res, k = @<k>)\", \"k = @<k>\")\n", code.pattern = "@<CODE>") }
knitr_insert_tabs()
```

MDS plots:

```{r @{top_method}-@{partition_method}-mds, results = "asis", echo = FALSE, include = TRUE}
@{ k = res_list@list[[1]]@k
qq("knitr_add_tab_item(\"dimension_reduction(res, k = @<k>)\", \"k = @<k>\")\n", code.pattern = "@<CODE>") }
knitr_insert_tabs()
```

Consistency of classes.

```{r @{top_method}-@{partition_method}-collect-classes}
collect_classes(res)
```



