<!--
%\VignetteEngine{knitr}
%\VignetteIndexEntry{3. Gene Ontology Enrichment to Signature Genes}
-->

Gene Ontology Enrichment to Signature Genes
=============================================================

**Author**: Zuguang Gu ( z.gu@dkfz.de )

**Date**: `r Sys.Date()`

**Package version**: `r installed.packages()["cola", "Version"]`

-------------------------------------------------------------

```{r, echo = FALSE, message = FALSE}
library(markdown)
library(knitr)
knitr::opts_chunk$set(
    error = FALSE,
    tidy  = FALSE,
    message = FALSE,
    fig.align = "center")
options(width = 100)
library(cola)
```


```{r, results = "hide"}
library(cola)
download.file("https://github.com/jokergoo/cola_examples/raw/master/TCGA_GBM/TCGA_GBM_subgroup.rds", 
    destfile = "TCGA_GBM_subgroup.rds", quiet = TRUE)
rl = readRDS("TCGA_GBM_subgroup.rds")
file.remove("TCGA_GBM_subgroup.rds")

res = rl["ATC:skmeans"]
```

```{r}
get_signatures(res)
```

```{r}
library(org.Hs.eg.db)
id_mapping = map_to_entrez_id("SYMBOL")
GO_enrichment(res, id_mapping = id_mapping)
```
