<!-- Generated by pkgdown: do not edit by hand -->
<!DOCTYPE html>
<html lang="en">
  <head>
  <meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>Get class IDs from the ConsensusPartitionList object — get_classes-ConsensusPartitionList-method • cola</title>


<!-- jquery -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<!-- Bootstrap -->

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha256-916EbMg70RQy9LHiGkXzG8hSg9EdNy97GazNG/aiY1w=" crossorigin="anonymous" />

<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script>

<!-- Font Awesome icons -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.1/css/all.min.css" integrity="sha256-nAmazAk6vS34Xqo0BSrTb+abbtFlgsFK7NKSi6o7Y78=" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.1/css/v4-shims.min.css" integrity="sha256-6qHlizsOWFskGlwVOKuns+D1nB6ssZrHQrNj1wGplHc=" crossorigin="anonymous" />

<!-- clipboard.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script>

<!-- headroom.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.4/headroom.min.js" integrity="sha256-DJFC1kqIhelURkuza0AvYal5RxMtpzLjFhsnVIeuk+U=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.4/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script>

<!-- pkgdown -->
<link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script>




<meta property="og:title" content="Get class IDs from the ConsensusPartitionList object — get_classes-ConsensusPartitionList-method" />
<meta property="og:description" content="Get class IDs from the ConsensusPartitionList object" />
<meta name="twitter:card" content="summary" />




<!-- mathjax -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script>

<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->



  </head>

  <body>
    <div class="container template-reference-topic">
      <header>
      <div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">cola</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">1.1.2</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="../index.html">
    <span class="fas fa fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/cola.html">Get started</a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="../articles/a_quick_start.html">UNKNOWN TITLE</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/jokergoo/cola">
    <span class="fab fa fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
      
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

      

      </header>

<div class="row">
  <div class="col-md-9 contents">
    <div class="page-header">
    <h1>Get class IDs from the ConsensusPartitionList object</h1>
    
    <div class="hidden name"><code>get_classes-ConsensusPartitionList-method.rd</code></div>
    </div>

    <div class="ref-description">
    <p>Get class IDs from the ConsensusPartitionList object</p>
    </div>

    <pre class="usage"><span class='co'># S4 method for ConsensusPartitionList</span>
<span class='fu'><a href='get_classes-dispatch.rd.html'>get_classes</a></span>(<span class='no'>object</span>, <span class='no'>k</span>)</pre>

    <h2 class="hasAnchor" id="arguments"><a class="anchor" href="#arguments"></a>Arguments</h2>
    <table class="ref-arguments">
    <colgroup><col class="name" /><col class="desc" /></colgroup>
    <tr>
      <th>object</th>
      <td><p>A <code><a href='ConsensusPartitionList-class.rd.html'>ConsensusPartitionList-class</a></code> object.</p></td>
    </tr>
    <tr>
      <th>k</th>
      <td><p>Number of partitions.</p></td>
    </tr>
    </table>

    <h2 class="hasAnchor" id="details"><a class="anchor" href="#details"></a>Details</h2>

    <p>The class IDs are inferred by merging partitions from all methods
by weighting the mean silhouette scores in each method.</p>
    <h2 class="hasAnchor" id="value"><a class="anchor" href="#value"></a>Value</h2>

    <p>A data frame with class IDs and other columns which are entropy of the percent membership matrix
and the silhouette scores which measure the stability of a sample to stay in its group.</p>

    <h2 class="hasAnchor" id="examples"><a class="anchor" href="#examples"></a>Examples</h2>
    <pre class="examples"><div class='input'><span class='fu'><a href='https://rdrr.io/r/utils/data.html'>data</a></span>(<span class='no'>cola_rl</span>)
<span class='fu'><a href='get_classes-dispatch.rd.html'>get_classes</a></span>(<span class='no'>cola_rl</span>, <span class='kw'>k</span> <span class='kw'>=</span> <span class='fl'>2</span>)</div><div class='output co'>#&gt;    class   entropy silhouette
#&gt; 1      1 0.8757769  0.7216889
#&gt; 2      1 0.8722839  0.7216889
#&gt; 3      1 0.8567034  0.7216889
#&gt; 4      1 0.8145741  0.7297331
#&gt; 5      1 0.9026515  0.6747563
#&gt; 6      1 0.7648975  0.7314622
#&gt; 7      1 0.7963628  0.7216889
#&gt; 8      1 0.9016023  0.6747563
#&gt; 9      1 0.8727311  0.7216889
#&gt; 10     1 0.8634292  0.7216889
#&gt; 11     1 0.7968682  0.7304181
#&gt; 12     1 0.8735814  0.7216889
#&gt; 13     1 0.9009910  0.6747563
#&gt; 14     1 0.8674075  0.7216889
#&gt; 15     1 0.8854927  0.6747563
#&gt; 16     1 0.8889275  0.7216889
#&gt; 17     1 0.8679847  0.7216889
#&gt; 18     1 0.8744266  0.7216889
#&gt; 19     1 0.8724000  0.7216889
#&gt; 20     1 0.9046701  0.6747563
#&gt; 21     2 0.2404484  0.9958845
#&gt; 22     2 0.2498779  0.9958845
#&gt; 23     2 0.4548754  0.9958845
#&gt; 24     2 0.2343467  0.9958845
#&gt; 25     2 0.2809653  0.9958845
#&gt; 26     2 0.2737365  0.9958845
#&gt; 27     2 0.3656621  0.9958845
#&gt; 28     2 0.2613917  0.9958845
#&gt; 29     2 0.2378379  0.9958845
#&gt; 30     2 0.3995010  0.9958845
#&gt; 31     2 0.4821843  0.9958845
#&gt; 32     2 0.3020918  0.9958845
#&gt; 33     2 0.2607409  0.9958845
#&gt; 34     2 0.2646854  0.9958845
#&gt; 35     2 0.2630202  0.9958845
#&gt; 36     2 0.3977701  0.9958845
#&gt; 37     2 0.5057282  0.9192652
#&gt; 38     2 0.2980815  0.9958845
#&gt; 39     2 0.4244982  0.9958845
#&gt; 40     2 0.3281018  0.9958845
#&gt; 41     1 0.9110809  0.6081422
#&gt; 42     1 0.9170792  0.5445998
#&gt; 43     1 0.9457887  0.4651221
#&gt; 44     1 0.6981407  0.7126858
#&gt; 45     1 0.8038979  0.6916830
#&gt; 46     1 0.8086876  0.6916830
#&gt; 47     1 0.7854909  0.7126858
#&gt; 48     1 0.9731646  0.4651221
#&gt; 49     1 0.9491938  0.4651221
#&gt; 50     1 0.6954144  0.7159608
#&gt; 51     1 0.8730131  0.6081422
#&gt; 52     1 0.5528623  0.7159608
#&gt; 53     1 0.7464347  0.7126858
#&gt; 54     1 0.9939087  0.3585014
#&gt; 55     1 0.9978902  0.2237671
#&gt; 56     1 0.6949971  0.7126858
#&gt; 57     1 0.5999630  0.7159608
#&gt; 58     1 0.8226597  0.6558331
#&gt; 59     1 0.7914602  0.6916830
#&gt; 60     1 0.7345008  0.7126858</div></pre>
  </div>
  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
    <h2>Contents</h2>
    <ul class="nav nav-pills nav-stacked">
      <li><a href="#arguments">Arguments</a></li>
      <li><a href="#details">Details</a></li>
      <li><a href="#value">Value</a></li>
      <li><a href="#examples">Examples</a></li>
    </ul>

    <h2>Author</h2>
    <p>Zuguang Gu &lt;z.gu@dkfz.de&gt;</p>
  </div>
</div>


      <footer>
      <div class="copyright">
  <p>Developed by Zuguang Gu.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.4.1.</p>
</div>

      </footer>
   </div>

  


  </body>
</html>


