# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gene_cooccurrence_in_geneset <- function(match_mat) {
    .Call('cola_gene_cooccurrence_in_geneset', PACKAGE = 'cola', match_mat)
}

